adding type hints
marinaRomanchuk/instagram_own_version pull request #12
Opened 2022-02-21 15:12 UTC by marinaRomanchuk

2022-02-21 15:56 UTC, revimi requested changes

2022-02-21 15:56 UTC, revimi commented on comments/admin.py
> +    list_display: tuple = ("text", "post", "timestamp", "user")
В таких случаях, где переменной сразу присваивается значение, обычно не ставят type hints

2022-02-21 15:56 UTC, revimi commented on posts/serializers.py
> +    def create(self, data: dict) -> Post:
```suggestion
    def create(self, data: Dict[str, str]) -> Post:
```

2022-02-21 15:56 UTC, revimi commented on posts/tests.py
> +    def authenticate(self, login_data: dict) -> None:
В тестах type hints можно опустить, там обычно важнее скорость их написания

2022-02-21 18:10 UTC, marinaRomanchuk commented on posts/serializers.py
> +    def create(self, data: dict) -> Post:
Done

2022-02-21 18:15 UTC, marinaRomanchuk commented on comments/admin.py
> +    list_display: tuple = ("text", "post", "timestamp", "user")
Removed

2022-02-21 18:15 UTC, marinaRomanchuk commented on posts/tests.py
> +    def authenticate(self, login_data: dict) -> None:
Removed

2022-02-22 10:21 UTC, revimi approved these changes

2022-02-22 10:23 UTC, merged